import {readFile,readdir,stat} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve('dist');
async function walk(dir){return(await Promise.all((await readdir(dir,{withFileTypes:true})).map(e=>e.isDirectory()?walk(path.join(dir,e.name)):path.join(dir,e.name)))).flat();}
const files=await walk(root),html=files.filter(f=>f.endsWith('.html'));let links=0;
for(const file of html){const body=await readFile(file,'utf8');for(const regex of [/<title>[^<]+<\/title>/,/<html lang="zh-CN"/,/name="description"/,/name="viewport"/])assert.match(body,regex);
 for(const [,url]of body.matchAll(/(?:href|src)="([^"#]+)"/g)){if(!url.startsWith('/')||url.startsWith('//'))continue;const p=url.split(/[?#]/)[0];let target=path.join(root,decodeURIComponent(p));if(p.endsWith('/'))target=path.join(target,'index.html');assert.ok((await stat(target).catch(()=>null))?.isFile(),`${path.relative(root,file)} has broken local link: ${url}`);links++;}
 // Validate TOC/other fragment references against their generated IDs.
 const ids=new Set([...body.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));for(const [,hash]of body.matchAll(/href="#([^"]+)"/g))assert.ok(ids.has(decodeURIComponent(hash)),`Broken anchor in ${file}: ${hash}`);
}
for(const required of ['index.html','articles/index.html','articles/cs229-learning-plan/index.html','series/index.html','series/cs229/index.html','products/index.html','links/index.html','about/index.html','preferences/index.html','search/index.html','feed.xml','sitemap.xml'])assert.ok(files.includes(path.join(root,required)),`Missing ${required}`);
const home=await readFile(path.join(root,'index.html'),'utf8');assert.ok(home.includes('article-note')&&home.includes('/articles/cs229-learning-plan/')&&home.includes('/series/cs229/'));
const post=await readFile(path.join(root,'articles/cs229-learning-plan/index.html'),'utf8');assert.equal((post.match(/data-course-step=/g)||[]).length,31,'All detailed learning steps must be retained');assert.equal((post.match(/class="course-detail"/g)||[]).length,6);assert.ok(post.includes('CS229 · Course Map')&&post.includes('系列总览'));assert.ok(!post.includes('<pre'),'Overview workflows must be readable prose');assert.ok(post.includes('data-view-count')&&post.includes('reading-progress')&&post.includes('article-toc'));assert.ok(post.includes('SVM')&&post.includes('学生解答'));const styles=(await Promise.all(files.filter(f=>f.endsWith('.css')).map(f=>readFile(f,'utf8')))).join('');assert.ok(!/\.paper-backdrop[^}]*gradient/.test(styles),'Shared background must contain illustrations only');const backdrop=home.match(/<div class="paper-backdrop"[\s\S]*?<\/div>/)?.[0];assert.ok(backdrop);for(const page of ['articles/index.html','articles/cs229-learning-plan/index.html','series/cs229/index.html','products/index.html','links/index.html','about/index.html'])assert.ok((await readFile(path.join(root,page),'utf8')).includes(backdrop),'Pages must share exactly the same backdrop');
const sitemap=await readFile(path.join(root,'sitemap.xml'),'utf8');assert.ok(!/\/(collections|room|works|lab|notes|research|projects|preferences|search)\//.test(sitemap),'Retired/utility pages must not be advertised');
const bookmarks=await readFile(path.join(root,'links/index.html'),'utf8');assert.ok(bookmarks.includes('https://manboweb3.com/r/XASCAU'));assert.ok(!bookmarks.includes('cs229.stanford.edu')&&!bookmarks.includes('Study Edition'));
const feed=await readFile(path.join(root,'feed.xml'),'utf8');assert.ok(feed.includes('/articles/cs229-learning-plan/'));assert.ok(!feed.includes('about-this-space'));
for(const page of ['index.html','products/index.html','articles/index.html','about/index.html']){const body=await readFile(path.join(root,page),'utf8');assert.ok(!/rcloneForLinux|llm_compress|CS336|轨道之间|微小的生命|回声记忆/.test(body),'Unattributed demo work must not appear');}
console.log(`PASS: ${html.length} HTML pages, ${links} local references, anchors, 31 folded CS229 steps, series, products, bookmarks, reader counter, search, RSS and sitemap.`);
